<?php

namespace AppBundle\Repository;

/**
 * Answer_commentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Answer_commentRepository extends \Doctrine\ORM\EntityRepository
{
}
