<?php

namespace AppBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findcomment(){
        return $this->createQueryBuilder('comment')
             ->select('comment.id', 'comment.tableName','comment.userName','SUM(comment.likeN)')
           /* ->leftJoin('comment.newsId','news')*/
            ->groupBy('comment.newsId')
            ->setMaxResults(3)
            ->getQuery()  //tochka posle zaprosa
            ->getResult();
    }
    public function finduser(){
      /*  $sql = "SELECT id, user_name , sum(like_n) FROM `comment` group by user_name";*/
        return  $this->createQueryBuilder('comment')
            ->select('comment.id', 'comment.tableName','comment.userName', 'SUM(comment.likeN)')
            ->groupBy('comment.userName')
            ->setMaxResults(3)
            ->getQuery()  //tochka posle zaprosa
            ->getResult();
    }
}
