<?php

namespace AppBundle\Repository;

/**
 * HomeworksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HomeworksRepository extends \Doctrine\ORM\EntityRepository
{
    public function findSort(){
      return  $this->createQueryBuilder('homeworks')->addOrderBy('category_id', 'ASC')
            ->getQuery()  //tochka posle zaprosa
            ->getResult(); //rezyl'tat
    }
}
