<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function finduser($email, $password){
       // dump($email);

        $collections = $this->createQueryBuilder('user')
            ->where('user.password LIKE :in')
            ->andWhere('user.email =:identifier')
            ->setParameter('in', $password)
            ->setParameter('identifier',$email)
            ->getQuery()
            ->execute();

        return $collections;
    }
}
